name: IPython application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: I don't know what this does
      uses: actions/checkout@v2
    - name: Set up Python 3.7.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.10
    - name: Install dependencies
      run: |
        make install
    - name: Lint with Pylint
      run: |
        make lint 
    - name: Format code with Python black
      run: |
        make format
          
          
        
